version: 2

updates:
  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'weekly'
    
    open-pull-requests-limit: 5
    target-branch: 'dev'
    commit-message:
      prefix: 'deps'
    
    assignees:
      - 'philvessey'
    reviewers:
      - 'philvessey'