DROP TABLE IF EXISTS GTFS_AGENCY;

CREATE TABLE GTFS_AGENCY 
(
    Id VARCHAR(255), 
    Name VARCHAR(255) NOT NULL, 
    URL VARCHAR(255) NOT NULL, 
    Timezone VARCHAR(255) NOT NULL, 
    LanguageCode VARCHAR(255), 
    Phone VARCHAR(255), 
    FareURL VARCHAR(255), 
    Email VARCHAR(255)
);

DROP TABLE IF EXISTS GTFS_CALENDAR;

CREATE TABLE GTFS_CALENDAR 
(
    ServiceId VARCHAR(255) PRIMARY KEY, 
    Monday SMALLINT NOT NULL, 
    Tuesday SMALLINT NOT NULL, 
    Wednesday SMALLINT NOT NULL, 
    Thursday SMALLINT NOT NULL, 
    Friday SMALLINT NOT NULL, 
    Saturday SMALLINT NOT NULL, 
    Sunday SMALLINT NOT NULL, 
    StartDate DATE NOT NULL, 
    EndDate DATE NOT NULL
);

DROP TABLE IF EXISTS GTFS_CALENDAR_DATE;

CREATE TABLE GTFS_CALENDAR_DATE
(
    ServiceId VARCHAR(255) NOT NULL,
    ExceptionDate DATE NOT NULL,
    ExceptionType SMALLINT NOT NULL
);

DROP TABLE IF EXISTS GTFS_FARE_ATTRIBUTE;

CREATE TABLE GTFS_FARE_ATTRIBUTE
(
    FareId VARCHAR(255) NOT NULL,
    Price REAL NOT NULL,
    CurrencyType VARCHAR(255) NOT NULL,
    PaymentMethod SMALLINT NOT NULL,
    Transfers SMALLINT NOT NULL,
    AgencyId VARCHAR(255),
    TransferDuration SMALLINT
);

DROP TABLE IF EXISTS GTFS_FARE_RULE;

CREATE TABLE GTFS_FARE_RULE
(
    FareId VARCHAR(255) NOT NULL,
    RouteId VARCHAR(255),
    OriginId VARCHAR(255),
    DestinationId VARCHAR(255),
    ContainsId VARCHAR(255)
);

DROP TABLE IF EXISTS GTFS_FREQUENCY;

CREATE TABLE GTFS_FREQUENCY
(
    TripId VARCHAR(255) NOT NULL,
    StartTime VARCHAR(255) NOT NULL,
    EndTime VARCHAR(255) NOT NULL,
    HeadwaySecs SMALLINT NOT NULL,
    ExactTimes SMALLINT
);

DROP TABLE IF EXISTS GTFS_LEVEL;

CREATE TABLE GTFS_LEVEL
(
    Id VARCHAR(255) NOT NULL,
    Idx REAL NOT NULL,
    Name VARCHAR(255)
);

DROP TABLE IF EXISTS GTFS_PATHWAY;

CREATE TABLE GTFS_PATHWAY
(
    Id VARCHAR(255) NOT NULL,
    FromStopId VARCHAR(255) NOT NULL,
    ToStopId VARCHAR(255) NOT NULL,
    PathwayMode SMALLINT NOT NULL,
    IsBidirectional SMALLINT NOT NULL,
    Length REAL,
    TraversalTime SMALLINT,
    StairCount SMALLINT,
    MaxSlope REAL,
    MinWidth REAL,
    SignpostedAs VARCHAR(255),
    ReversedSignpostedAs VARCHAR(255)
);

DROP TABLE IF EXISTS GTFS_ROUTE;

CREATE TABLE GTFS_ROUTE
(
    Id VARCHAR(255) PRIMARY KEY,
    AgencyId VARCHAR(255),
    ShortName VARCHAR(255),
    LongName VARCHAR(255),
    Description VARCHAR(255),
    Type SMALLINT NOT NULL,
    Url VARCHAR(255),
    Color SMALLINT,
    TextColor SMALLINT
);

DROP TABLE IF EXISTS GTFS_SHAPE;

CREATE TABLE GTFS_SHAPE
(
    Id VARCHAR(255) NOT NULL,
    Longitude REAL NOT NULL,
    Latitude REAL NOT NULL,
    Sequence SMALLINT NOT NULL,
    DistanceTravelled REAL
);

DROP TABLE IF EXISTS GTFS_STOP;

CREATE TABLE GTFS_STOP
(
    Id VARCHAR(255) PRIMARY KEY,
    Code VARCHAR(255),
    Name VARCHAR(255),
    Description VARCHAR(255),
    Longitude REAL,
    Latitude REAL,
    Zone VARCHAR(255),
    Url VARCHAR(255),
    LocationType SMALLINT,
    ParentStation VARCHAR(255),
    Timezone VARCHAR(255),
    WheelchairBoarding SMALLINT,
    LevelId VARCHAR(255),
    PlatformCode VARCHAR(255)
);

DROP TABLE IF EXISTS GTFS_STOP_TIME;

CREATE TABLE GTFS_STOP_TIME
(
    TripId VARCHAR(255) NOT NULL,
    ArrivalTime VARCHAR(255),
    DepartureTime VARCHAR(255),
    StopId VARCHAR(255),
    StopSequence SMALLINT NOT NULL,
    StopHeadsign VARCHAR(255),
    PickupType SMALLINT,
    DropOffType SMALLINT,
    ShapeDistTravelled REAL,
    TimepointType SMALLINT
);

DROP TABLE IF EXISTS GTFS_TRANSFER;

CREATE TABLE GTFS_TRANSFER
(
    FromStopId VARCHAR(255),
    ToStopId VARCHAR(255),
    TransferType SMALLINT NOT NULL,
    MinimumTransferTime SMALLINT
);

DROP TABLE IF EXISTS GTFS_TRIP;

CREATE TABLE GTFS_TRIP
(
    Id VARCHAR(255) PRIMARY KEY,
    RouteId VARCHAR(255) NOT NULL,
    ServiceId VARCHAR(255) NOT NULL,
    Headsign VARCHAR(255),
    ShortName VARCHAR(255),
    Direction SMALLINT,
    BlockId VARCHAR(255),
    ShapeId VARCHAR(255),
    AccessibilityType SMALLINT
);